; -*- mode: Lisp -*-
((c++-mode (c-basic-offset . 2)
           (c-offsets-alist
            (access-label . -)
            (arglist-intro . +)
            (arglist-cont-nonempty . c-lineup-arglist)
            (defun-block-intro . +)
            (inclass . +)
            (innamespace . +)
            (statement-block-intro . +)
            (statement-case-intro . +)
            (statement-cont . +)
            (substatement . +)
            (topmost-intro . 0)
            (topmost-intro-cont . 0)
            (member-init-intro . +)
           )))
